[workspace]
members = [
    "crates/app",
    "crates/core",
    "crates/math",
    "crates/world",
    "crates/simulation",
    "crates/renderer",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
publish = false

[workspace.dependencies]
anyhow = "1.0"
criterion = { version = "0.8.2", default-features = false }
egui = "0.36.2"
egui-wgpu = "0.36.2"
egui-winit = { version = "0.36.2", default-features = false, features = ["wayland", "x11"] }
glam = "0.30"
naga = { version = "30", features = ["wgsl-in"] }
pollster = "0.4"
png = "0.18"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu = "30"
winit = "0.30"
slint = { version = "=1.18.1", default-features = false, features = ["std", "compat-1-2", "accessibility", "backend-winit", "renderer-femtovg-wgpu", "unstable-wgpu-30"] }
slint-build = "=1.18.1"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"
