[package]
name = "mundaris_renderer"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
pollster.workspace = true
thiserror.workspace = true
tracing.workspace = true
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
