[package]
name = "mundaris_math"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
glam.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "reference_frames"
harness = false

[[bench]]
name = "terrain_noise"
harness = false

[lints]
workspace = true
